- hosts: all
  gather_facts: False

  tasks:
    - name: Terminate each instance
      local_action:
        module: ec2
        state: absent
        instance_ids: "{{ ec2_id }}"

    # These steps depend on the instances being removed, which is done 10-20
    # minutes after terminating

    # - name: Get subnet details
    #   local_action:
    #     module: ec2_vpc_subnet_facts
    #     filters:
    #       subnet-id: "{{ ec2_subnet_id }}"
    #   register: subnet
    #   run_once: True
    #
    # - name: Remove subnet for demo servers
    #   local_action:
    #     module: ec2_vpc_subnet
    #     state: absent
    #     vpc_id: "{{ ec2_vpc_id }}"
    #     cidr: "{{ subnet.subnets[0].cidr_block }}"
    #   run_once: True
    #
    # - name: Remove Demo VPC
    #   local_action:
    #     module: ec2_vpc
    #     state: absent
    #     vpc_id: "{{ ec2_vpc_id }}"
    #     resource_tags:
    #   run_once: True
